### ISSUE TITLE
Add opt-level for dev builds

### ISSUE THREAD

**Issue by observant2** [dpogretskiy/specs-ggez-showcase#2]
When you add
```toml
[profile.dev]
opt-level = 2
```
to the cargo.toml, the game starts *much* quicker (on my machine at least). I think this is a known problem with ggez.
